### ISSUE TITLE
STAMPs v1 Launch CheckList

### ISSUE THREAD

**Issue by twilson63** [twilson63/stamp-protocol#11]
- [ ] Update Contract based on https://g8way.io/Cl_qf8zj2tUTtS13EyRAstRXWLieEcB_v7N1sRePqPo 
- [ ] Update Deploy to set Manifest SEQUENCER ONLY transactions
- [ ] Update stamps.arweave.dev to a community-driven content system (based on SPECS)
- [ ] Post Info Articles on the STAMPs community site
  - README
  - Tokenomics
  - SDK
  - Specification
- [ ] Get community audit on STAMPs source code
